=== arthurfiddich/simplenlg/res/xml/RealizerSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
	<!--
		Schema for simplenlg edited by Christopher Howell (Agfa Healthcare
		Corporation)
	-->
<xs:schema targetNamespace="http://code.google.com/p/simplenlg/schemas/version1"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:nlg="http://code.google.com/p/simplenlg/schemas/version1">
	<xs:element name="NLGSpec">
		<xs:complexType>
			<xs:choice>
				<xs:element name="Request" type="nlg:RequestType" />
				<xs:element name="Recording" type="nlg:RecordSet" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RequestType">
		<xs:sequence>
			<xs:element name="Document" type="nlg:DocumentElement"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RecordSet">
		<xs:sequence>
			<xs:element name="Record" type="nlg:DocumentRealisation"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="DocumentRealisation">
		<xs:sequence>
			<xs:element name="Document" type="nlg:DocumentElement"
				maxOccurs="1" minOccurs="1" />
			<xs:element name="Realisation" type="xs:string" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="DocumentElement">
		<xs:complexContent>
			<xs:extension base="nlg:NLGElement">
				<xs:sequence>
					<xs:element name="child" type="nlg:NLGElement"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attributeGroup ref="nlg:docAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="docAtts">
		<xs:attribute name="cat" type="nlg:documentCategory" />
		<xs:attribute name="title" type="xs:string" />
	</xs:attributeGroup>
	<xs:complexType name="SPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence>
					<xs:element name="cuePhrase" type="nlg:NLGElement"
						minOccurs="0" />
					<xs:element name="subj" type="nlg:NLGElement" minOccurs="0"
						maxOccurs="unbounded" />
					<xs:element name="vp" type="nlg:NLGElement" />
				</xs:sequence>
				<xs:attributeGroup ref="nlg:sPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="sPhraseAtts">
		<xs:attribute name="CLAUSE_STATUS" type="nlg:clauseStatus" />
		<xs:attribute name="COMPLEMENTISER" type="xs:string" />
		<xs:attribute name="FORM" type="nlg:form" />
		<xs:attribute name="INTERROGATIVE_TYPE" type="nlg:interrogativeType" />
		<xs:attribute name="MODAL" type="xs:string" />
		<xs:attribute name="NEGATED" type="xs:boolean" />
		<xs:attribute name="PASSIVE" type="xs:boolean" />
		<xs:attribute name="PERFECT" type="xs:boolean" />
		<xs:attribute name="PERSON" type="nlg:person" />
		<xs:attribute name="PROGRESSIVE" type="xs:boolean" />
		<xs:attribute name="TENSE" type="nlg:tense" />

	</xs:attributeGroup>
	<xs:complexType name="VPPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence />
				<xs:attributeGroup ref="nlg:vpPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="vpPhraseAtts">
		<xs:attribute name="FORM" type="nlg:form" />
		<xs:attribute name="MODAL" type="xs:string" />
		<xs:attribute name="NEGATED" type="xs:boolean" />
		<xs:attribute name="PASSIVE" type="xs:boolean" />
		<xs:attribute name="PERFECT" type="xs:boolean" />
		<xs:attribute name="PERSON" type="nlg:person" />
		<xs:attribute name="PROGRESSIVE" type="xs:boolean" />
		<xs:attribute name="TENSE" type="nlg:tense" />
	</xs:attributeGroup>
	<xs:complexType name="NPPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence>
					<xs:element name="spec" type="nlg:NLGElement" minOccurs="0" />
				</xs:sequence>
				<xs:attributeGroup ref="nlg:npPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="npPhraseAtts">
		<xs:attribute name="ADJECTIVE_ORDERING" type="xs:boolean" />
		<xs:attribute name="ELIDED" type="xs:boolean" />
		<xs:attribute name="NUMBER" type="nlg:numberAgreement" />
		<xs:attribute name="GENDER" type="nlg:gender"></xs:attribute>
		<xs:attribute name="PERSON" type="nlg:person" />
		<xs:attribute name="POSSESSIVE" type="xs:boolean" />
		<xs:attribute name="PRONOMINAL" type="xs:boolean" />
	</xs:attributeGroup>
	<xs:complexType name="AdjPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence />
				<xs:attributeGroup ref="nlg:adjAdvPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="adjAdvPhraseAtts">
		<xs:attribute name="IS_COMPARATIVE" type="xs:boolean" />
		<xs:attribute name="IS_SUPERLATIVE" type="xs:boolean" />
	</xs:attributeGroup>
	<xs:complexType name="AdvPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence />
				<xs:attributeGroup ref="nlg:adjAdvPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PPPhraseSpec">
		<xs:complexContent>
			<xs:extension base="nlg:PhraseElement">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CoordinatedPhraseElement">
		<xs:complexContent>
			<xs:extension base="nlg:NLGElement">
				<xs:sequence>
					<xs:element name="coord" type="nlg:NLGElement"
						maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attributeGroup ref="nlg:CoordinatedPhraseAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="CoordinatedPhraseAtts">
		<xs:attribute name="conj" type="xs:string" default="and" />
		<xs:attribute name="cat" type="nlg:phraseCategory" />
		<xs:attribute name="PERSON" type="nlg:person" />
		<xs:attribute name="POSSESSIVE" type="xs:boolean"></xs:attribute>
	</xs:attributeGroup>
	<xs:complexType name="PhraseElement" abstract="true">
		<xs:complexContent>
			<xs:extension base="nlg:NLGElement">
				<xs:sequence>
					<xs:element name="frontMod" type="nlg:NLGElement"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="preMod" type="nlg:NLGElement"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="head" type="nlg:WordElement"
						minOccurs="0" />
					<xs:element name="compl" type="nlg:NLGElement"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="postMod" type="nlg:NLGElement"
						minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="cat" type="nlg:phraseCategory" />
				<xs:attribute name="discourseFunction" type="nlg:discourseFunction"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StringElement">
		<xs:complexContent>
			<xs:extension base="nlg:NLGElement">
				<xs:sequence>
					<xs:element name="val" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NLGElement" abstract="true">
		<xs:sequence />
	</xs:complexType>
	<xs:complexType name="WordElement">
		<xs:complexContent>
			<xs:extension base="nlg:NLGElement">
				<xs:sequence>
					<xs:element name="base" type="xs:string" />
				</xs:sequence>
				<xs:attributeGroup ref="nlg:wordAtts" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:attributeGroup name="wordAtts">
		<xs:attribute name="cat" type="nlg:lexicalCategory" />
		<xs:attribute name="id" type="xs:string" />
		<xs:attribute name="EXPLETIVE_SUBJECT" type="xs:boolean" />
		<xs:attribute name="PROPER" type="xs:boolean" />
		<xs:attribute name="var" type="nlg:inflection" />
	</xs:attributeGroup>
	<xs:simpleType name="phraseCategory">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CLAUSE" />
			<xs:enumeration value="ADJECTIVE_PHRASE" />
			<xs:enumeration value="ADVERB_PHRASE" />
			<xs:enumeration value="NOUN_PHRASE" />
			<xs:enumeration value="PREPOSITIONAL_PHRASE" />
			<xs:enumeration value="VERB_PHRASE" />
			<xs:enumeration value="CANNED_TEXT" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tense">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FUTURE" />
			<xs:enumeration value="PAST" />
			<xs:enumeration value="PRESENT" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="clauseStatus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MATRIX" />
			<xs:enumeration value="SUBORDINATE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="discourseFunction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AUXILIARY" />
			<xs:enumeration value="COMPLEMENT" />
			<xs:enumeration value="CONJUNCTION" />
			<xs:enumeration value="CUE_PHRASE" />
			<xs:enumeration value="FRONT_MODIFIER" />
			<xs:enumeration value="HEAD" />
			<xs:enumeration value="INDIRECT_OBJECT" />
			<xs:enumeration value="OBJECT" />
			<xs:enumeration value="PRE_MODIFIER" />
			<xs:enumeration value="POST_MODIFIER" />
			<xs:enumeration value="SPECIFIER" />
			<xs:enumeration value="SUBJECT" />
			<xs:enumeration value="VERB_PHRASE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="documentCategory">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DOCUMENT" />
			<xs:enumeration value="SECTION" />
			<xs:enumeration value="PARAGRAPH" />
			<xs:enumeration value="SENTENCE" />
			<xs:enumeration value="LIST" />
			<xs:enumeration value="LIST_ITEM" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="form">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BARE_INFINITIVE" />
			<xs:enumeration value="GERUND" />
			<xs:enumeration value="IMPERATIVE" />
			<xs:enumeration value="INFINITIVE" />
			<xs:enumeration value="NORMAL" />
			<xs:enumeration value="PAST_PARTICIPLE" />
			<xs:enumeration value="PRESENT_PARTICIPLE" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="gender">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MASCULINE" />
			<xs:enumeration value="FEMININE" />
			<xs:enumeration value="NEUTER" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lexicalCategory">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ANY" />
			<xs:enumeration value="SYMBOL" />
			<xs:enumeration value="NOUN" />
			<xs:enumeration value="ADJECTIVE" />
			<xs:enumeration value="ADVERB" />
			<xs:enumeration value="VERB" />
			<xs:enumeration value="DETERMINER" />
			<xs:enumeration value="PRONOUN" />
			<xs:enumeration value="CONJUNCTION" />
			<xs:enumeration value="PREPOSITION" />
			<xs:enumeration value="COMPLEMENTISER" />
			<xs:enumeration value="MODAL" />
			<xs:enumeration value="AUXILIARY" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="numberAgreement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOTH" />
			<xs:enumeration value="PLURAL" />
			<xs:enumeration value="SINGULAR" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="person">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FIRST" />
			<xs:enumeration value="SECOND" />
			<xs:enumeration value="THIRD" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="interrogativeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HOW" />
			<xs:enumeration value="WHAT_OBJECT" />
			<xs:enumeration value="WHAT_SUBJECT" />
			<xs:enumeration value="WHERE" />
			<xs:enumeration value="WHO_INDIRECT_OBJECT" />
			<xs:enumeration value="WHO_OBJECT" />
			<xs:enumeration value="WHO_SUBJECT" />
			<xs:enumeration value="WHY" />
			<xs:enumeration value="YES_NO" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="inflection">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GRECO_LATIN_REGULAR" />
			<xs:enumeration value="IRREGULAR" />
			<xs:enumeration value="REGULAR" />
			<xs:enumeration value="REGULAR_DOUBLE" />
			<xs:enumeration value="UNCOUNT" />
			<xs:enumeration value="INVARIANT" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== arthurfiddich/simplenlg/tests/clauseTests.xml
<?xml version="1.0" encoding="utf-8"?>
<nlg:NLGSpec xmlns="http://code.google.com/p/simplenlg/schemas/version1"
	xmlns:nlg="http://code.google.com/p/simplenlg/schemas/version1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 RealizerSchema.xsd ">

	<nlg:Recording name="Clause tests">

		<nlg:Record name="Negation on VP">
			<Document cat="PARAGRAPH">
				<child xsi:type="SPhraseSpec">
					<subj xsi:type="NPPhraseSpec">
						<head cat="NOUN">
							<base>patient</base>
						</head>
						<spec xsi:type="WordElement" cat="DETERMINER">
							<base>the</base>
						</spec>
					</subj>
					<vp xsi:type="VPPhraseSpec" TENSE="PAST" NEGATED="true">
						<head cat="VERB" var="IRREGULAR">
							<base>lie</base>
						</head>
						<postMod xsi:type="VPPhraseSpec" TENSE="PAST">
							<head cat="VERB">
								<base>etherise</base>
							</head>
							<postMod xsi:type="PPPhraseSpec">
								<head cat="PREPOSITION">
									<base>upon</base>
								</head>
								<compl xsi:type="NPPhraseSpec">
									<head cat="NOUN">
										<base>table</base>
									</head>
									<spec xsi:type="WordElement" cat="DETERMINER">
										<base>a</base>
									</spec>
								</compl>
							</postMod>
						</postMod>
					</vp>
				</child>
			</Document>
		</nlg:Record>

		<nlg:Record name="Negation on S">
			<Document cat="PARAGRAPH">
				<child xsi:type="SPhraseSpec" TENSE="PAST" NEGATED="true">
					<subj xsi:type="NPPhraseSpec">
						<head cat="NOUN">
							<base>patient</base>
						</head>
						<spec xsi:type="WordElement" cat="DETERMINER">
							<base>the</base>
						</spec>
					</subj>
					<vp xsi:type="VPPhraseSpec">
						<head cat="VERB">
							<base>lie</base>
						</head>
						<postMod xsi:type="VPPhraseSpec" TENSE="PAST">
							<head cat="VERB">
								<base>etherise</base>
							</head>
							<postMod xsi:type="PPPhraseSpec">
								<head cat="PREPOSITION">
									<base>upon</base>
								</head>
								<compl xsi:type="NPPhraseSpec">
									<head cat="NOUN">
										<base>table</base>
									</head>
									<spec xsi:type="WordElement" cat="DETERMINER">
										<base>a</base>
									</spec>
								</compl>
							</postMod>
						</postMod>
					</vp>
				</child>
			</Document>
		</nlg:Record>

	</nlg:Recording>
</nlg:NLGSpec>

=== arthurfiddich/simplenlg/tests/activeTest.xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" cat="PARAGRAPH" xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd" xmlns="http://code.google.com/p/simplenlg/schemas/version1">
  <child xsi:type="SPhraseSpec">
    <subj xsi:type="NPPhraseSpec">
      <head cat="NOUN">patient</head>
      <spec cat="DETERMINER">the</spec>
    </subj>
    <vp xsi:type="VPPhraseSpec" TENSE="PAST">
      <head cat="VERB">lie</head>
      <postMod xsi:type="VPPhraseSpec" TENSE="PAST">
        <head cat="VERB">etherise</head>
        <postMod xsi:type="PPPhraseSpec">
          <head cat="PREPOSITION">upon</head>
          <compl xsi:type="NPPhraseSpec">
            <head cat="NOUN">table</head>
            <spec cat="DETERMINER">a</spec>
          </compl>
        </postMod>
      </postMod>
    </vp>
  </child>
  <child xsi:type="SPhraseSpec">
    <subj xsi:type="NPPhraseSpec">
      <head cat="NOUN">patient</head>
      <spec cat="DETERMINER">the</spec>
    </subj>
    <vp xsi:type="VPPhraseSpec" TENSE="PAST">
      <head cat="VERB" var="IRREGULAR">lie</head>
      <postMod xsi:type="VPPhraseSpec" TENSE="PAST">
        <head cat="VERB">etherise</head>
        <postMod xsi:type="PPPhraseSpec">
          <head cat="PREPOSITION">upon</head>
          <compl xsi:type="NPPhraseSpec">
            <head cat="NOUN">table</head>
            <spec cat="DETERMINER">a</spec>
          </compl>
        </postMod>
      </postMod>
    </vp>
  </child>
</Document>

=== arthurfiddich/simplenlg/tests/npTests.xml
<?xml version="1.0" encoding="utf-8"?>
<nlg:NLGSpec xmlns="http://code.google.com/p/simplenlg/schemas/version1"
	xmlns:nlg="http://code.google.com/p/simplenlg/schemas/version1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 RealizerSchema.xsd ">

	<Recording name="NPPhraseSpec examples">
		<Record name="Possessive Spec">
			<Document>
				<child xsi:type="NPPhraseSpec">
					<head xsi:type="WordElement" cat="NOUN" base="patient" />
					<spec xsi:type="NPPhraseSpec" POSSESSIVE="true">
						<head cat="NOUN" base="John" />
					</spec>
				</child>
			</Document>
		</Record>

		<Record name="Determiner Spec">
			<Document>
				<child xsi:type="NPPhraseSpec">
					<head xsi:type="WordElement" cat="NOUN" base="patient" />
					<spec xsi:type="WordElement" cat="DETERMINER" base="the" />
				</child>
			</Document>
		</Record>

		<Record name="Complex NP">
			<Document>
				<child xsi:type="NPPhraseSpec" number="PLURAL">
					<head xsi:type="WordElement" cat="NOUN" base="bone" />
					<spec xsi:type="CoordinatedPhraseElement" conj="and" POSSESSIVE="true">
						<coord xsi:type="NPPhraseSpec" PRONOMINAL="true">
							<head xsi:type="WordElement" cat="NOUN" base="dog" />
							<spec xsi:type="WordElement" cat="DETERMINER" base="the" />
						</coord>
						<coord xsi:type="NPPhraseSpec">
							<head xsi:type="WordElement" cat="NOUN" base="woman" />
							<spec xsi:type="WordElement" cat="DETERMINER" base="the" />
						</coord>
					</spec>
				</child>
			</Document>
		</Record>
	</Recording>
</nlg:NLGSpec>

=== arthurfiddich/simplenlg/tests/aProblem.xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" cat="PARAGRAPH" xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd" xmlns="http://code.google.com/p/simplenlg/schemas/version1">
  <child xsi:type="SPhraseSpec">
    <subj xsi:type="NPPhraseSpec">
      <head cat="ADVERB">there</head>
    </subj>
    <vp xsi:type="VPPhraseSpec">
      <head cat="VERB">be</head>
      <compl xsi:type="NPPhraseSpec">
        <preMod xsi:type="CoordinatedPhraseElement" conj=",">
          <coord xsi:type="AdjPhraseSpec">
            <head cat="ADJECTIVE">eccentric</head>
          </coord>
          <coord xsi:type="AdjPhraseSpec">
            <head cat="ADJECTIVE">tubular</head>
          </coord>
        </preMod>
        <head cat="NOUN">stenosis</head>
        <spec>a</spec>
      </compl>
      <postMod xsi:type="PPPhraseSpec">
        <head cat="PREPOSITION">in</head>
        <compl xsi:type="NPPhraseSpec">
          <head cat="NOUN">third obtuse marginal branch</head>
          <spec cat="DETERMINER">the</spec>
        </compl>
      </postMod>
    </vp>
  </child>
  <child xsi:type="SPhraseSpec">
    <subj xsi:type="NPPhraseSpec">
      <head cat="ADVERB">there</head>
    </subj>
    <vp xsi:type="VPPhraseSpec">
      <head cat="VERB">be</head>
      <compl xsi:type="NPPhraseSpec">
        <preMod xsi:type="StringElement">
          <val>an</val>
        </preMod>
        <preMod xsi:type="StringElement">
          <val>80 %</val>
        </preMod>
        <head cat="NOUN">stenosis</head>
      </compl>
      <postMod xsi:type="PPPhraseSpec">
        <head cat="PREPOSITION">in</head>
        <compl xsi:type="NPPhraseSpec">
          <preMod xsi:type="AdjPhraseSpec">
            <head cat="ADJECTIVE">proximal</head>
          </preMod>
          <head cat="NOUN">right coronary artery</head>
          <spec cat="DETERMINER">the</spec>
        </compl>
      </postMod>
    </vp>
  </child>
</Document>

=== arthurfiddich/simplenlg/testsrc/simplenlg/test/xmlrealiser/AppositiveTest.xml
<?xml version="1.0" encoding="utf-8"?>
<NLGSpec xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://simplenlg.googlecode.com/svn/trunk/res/xml D:\svnNLG\Client\NLGWrapper\RealizerSchema.xsd" xmlns="http://simplenlg.googlecode.com/svn/trunk/res/xml">
 <Recording name="">
   <Record name="">
    <Document cat="PARAGRAPH">
      <child xsi:type="SPhraseSpec" PASSIVE="true">
        <vp xsi:type="VPPhraseSpec" TENSE="PAST">
          <compl xsi:type="NPPhraseSpec">
            <postMod xsi:type="NPPhraseSpec" appositive="true">
              <head cat="NOUN">
                <base>D701000000992</base>
              </head>
              <spec xsi:type="WordElement" cat="DETERMINER">
                <base>the</base>
              </spec>
            </postMod>
            <head cat="NOUN">
              <base>angioplasty balloon catheter</base>
            </head>
            <spec xsi:type="WordElement" cat="DETERMINER">
              <base>a</base>
            </spec>
          </compl>
          <head cat="VERB">
            <base>deploy</base>
          </head>
        </vp>
      </child>
    </Document>
   </Record>
  </Recording>
</NLGSpec>

=== arthurfiddich/simplenlg/tests/Morph.xml
<?xml version="1.0" encoding="utf-8" ?>
-
<nl:Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" cat="LIST"
	xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd"
	xmlns:nl="http://code.google.com/p/simplenlg/schemas/version1">
	-
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		-
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>18</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>180</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	-
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		-
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>18x</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>08</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	-
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		-
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>11g</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			-
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>9i</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>8th</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>9th</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>11th</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>1100</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>11.000</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>11000</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>81000</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				-
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>180,000</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>81,000</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>01834</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>8%</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>9%</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
	<nl:child xsi:type="nl:DocumentElement" cat="LIST_ITEM"
		xsi:schemaLocation="http://code.google.com/p/simplenlg/schemas/version1 D:\svnNLG\XMLRealiser\RealizerSchema.xsd">
		<nl:child xsi:type="nl:CoordinatedPhraseElement" conj="but">
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>8432425</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
			<nl:coord xsi:type="nl:NPPhraseSpec">
				<nl:preMod xsi:type="nl:StringElement">
					<nl:val>42nd</nl:val>
				</nl:preMod>
				<nl:head cat="NOUN">thing</nl:head>
				<nl:spec cat="DETERMINER">a</nl:spec>
			</nl:coord>
		</nl:child>
	</nl:child>
</nl:Document>
